import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://askbluestg.bcbsa.com/');
  await page.locator('div').filter({ hasText: /^Yes, I'm a Member$/ }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Let\'s Get Started' }).click();
  await page.getByRole('radio', { name: 'I\'m employed' }).click();
  await page.getByRole('radio', { name: 'Department of Defense' }).click();
  await page.getByRole('radio', { name: 'Only I need health care' }).click();
  await expect(page.locator('h2')).toContainText('Keep in mind');
  await expect(page.locator('#questions-section')).toContainText('As you answer the following questions, please be sure to keep your current and future needs in mind.');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByLabel('Are you currently enrolled or')).toContainText('No');
  await expect(page.getByLabel('Are you currently enrolled or')).toContainText('Yes');
  await page.getByRole('radio', { name: 'No' }).click();
  await page.getByRole('checkbox', { name: 'None of the above' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('radio', { name: 'Yes, I plan on seeing a' }).click();
  await page.getByRole('radio', { name: 'Yes, I have an upcoming' }).click();
  await page.getByRole('radio', { name: 'Yes, I plan on giving birth' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('radio', { name: 'I want access to brand name' }).click();
  await page.getByRole('radio', { name: 'Yes, it\'s important to get my' }).click();
  await page.getByRole('radio', { name: 'Yes, I take specialty drugs.' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('radio', { name: 'I want the option of seeing' }).click();
  await page.getByRole('radio', { name: 'I\'m willing to pay a higher' }).click(); 
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('h1')).toContainText('FEP Blue Standard®');
  await expect(page.getByRole('navigation')).toBeVisible();
  await expect(page.locator('#summary-section div').filter({ hasText: 'Download or Print' }).nth(2)).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Based on your answers:' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'FEP Blue Standard Overview' })).toBeVisible();
  await expect(page.getByText('$174.81 Bi-Weekly (Self Only)')).toBeVisible();
  await expect(page.getByText('$174.81 Bi-Weekly (Self Only)')).toContainText('$174.81 Bi-Weekly (Self Only)');
  await expect(page.getByText('Enrollment code (Self Only)')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'FEP Blue Standard Overview' })).toBeVisible();
  await page.close();
});